import path from "node:path";
import { fileURLToPath } from "node:url";
import { randomUUID } from "node:crypto";
import { createDbRepository } from "../index";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDir, "../..");
const defaultDataDir = path.resolve(packageRoot, ".yurbrain-data", "db");
const defaultMigrationsPath = path.resolve(packageRoot, "migrations");

const databasePath = process.env.YURBRAIN_DB_PATH ?? defaultDataDir;
const migrationsPath = process.env.YURBRAIN_MIGRATIONS_PATH ?? defaultMigrationsPath;
const userId = process.env.YURBRAIN_SEED_USER_ID ?? "11111111-1111-1111-1111-111111111111";

async function main() {
  const repo = createDbRepository({ databasePath, migrationsPath });
  try {
    const now = new Date().toISOString();
    const itemId = randomUUID();
    const threadId = randomUUID();
    const taskId = randomUUID();
    const sessionId = randomUUID();

    await repo.createBrainItem({
      id: itemId,
      userId,
      type: "note",
      title: "Seeded brain item",
      rawContent: "Seed content for persistence verification.",
      status: "active",
      createdAt: now,
      updatedAt: now
    });

    await repo.appendEvent({
      id: randomUUID(),
      userId,
      eventType: "brain_item_created",
      payload: { id: itemId, type: "note", seeded: true },
      occurredAt: now
    });

    await repo.createThread({
      id: threadId,
      targetItemId: itemId,
      kind: "item_comment",
      createdAt: now,
      updatedAt: now
    });

    await repo.createMessage({
      id: randomUUID(),
      threadId,
      role: "user",
      content: "Seeded thread message",
      createdAt: now
    });

    await repo.createFeedCard({
      id: randomUUID(),
      userId,
      cardType: "item",
      lens: "all",
      itemId,
      title: "Seeded feed card",
      body: "Generated by @yurbrain/db db:seed",
      dismissed: false,
      createdAt: now
    });

    await repo.createTask({
      id: taskId,
      userId,
      sourceItemId: itemId,
      sourceMessageId: null,
      title: "Seeded task",
      status: "in_progress",
      createdAt: now,
      updatedAt: now
    });

    await repo.createSession({
      id: sessionId,
      taskId,
      state: "running",
      startedAt: now,
      endedAt: null
    });

    await repo.createArtifact({
      id: randomUUID(),
      itemId,
      type: "summary",
      payload: {
        content: "Seed summary artifact",
        metadata: { seeded: true }
      },
      confidence: 0.95,
      createdAt: now
    });

    console.log(`Seeded persistent data for user ${userId}`);
  } finally {
    await repo.close();
  }
}

main().catch((error) => {
  console.error("Failed to seed database", error);
  process.exit(1);
});
