[hasura]
version = "v2.33.0"
adminSecret = "{{ secrets.NHOST_ADMIN_SECRET }}"
webhookSecret = "{{ secrets.NHOST_WEBHOOK_SECRET }}"

[[hasura.jwtSecrets]]
type = "HS256"
key = "{{ secrets.NHOST_JWT_SECRET }}"
claims_namespace = "https://hasura.io/jwt/claims"

[hasura.resources]
compute.cpu = 500
compute.memory = 1024

[postgres]
version = "15"

[postgres.resources]
storage.capacity = 1
compute.cpu = 500
compute.memory = 1024

[auth]
enabled = true

[auth.resources]
compute.cpu = 500
compute.memory = 1024

[storage]
enabled = true

[storage.resources]
compute.cpu = 500
compute.memory = 1024

[observability]
grafana.enabled = false
