[hasura]
version = "v2.33.0"

[observability.grafana.alerting]
enabled = false

[postgres]
version = "15"

[postgres.resources.compute]
cpu = 500
memory = 1024

[postgres.resources.storage]
capacity = 1

[auth]
enabled = true

[storage]
enabled = true
