export const endpoints = {
  authMe: "/auth/me",
  captureIntake: "/capture/intake",
  brainItems: "/brain-items",
  feed: "/feed",
  founderReview: "/founder-review",
  threads: "/threads",
  messages: "/messages",
  preferences: "/preferences",
  preferencesMe: "/preferences/me",
  tasks: "/tasks",
  sessions: "/sessions",
  manualConvertTask: "/tasks/manual-convert",
  aiSummarize: "/ai/summarize",
  aiSummarizeCluster: "/ai/summarize-cluster",
  aiClassify: "/ai/classify",
  aiQuery: "/ai/query",
  aiNextStep: "/ai/next-step",
  aiConvert: "/ai/convert",
  functionFeed: "/functions/feed",
  functionFeedRank: "/functions/feed",
  functionFounderReview: "/functions/founder-review",
  functionSummarizeProgress: "/functions/summarize-progress",
  functionNextStep: "/functions/what-should-i-do-next",
  functionSessionHelper: "/functions/session-helper"
} as const;
